### ISSUE TITLE
Couple of feedback points on time machine post

### ISSUE THREAD

**Issue by chmac** [alubbock/samba-docker#1]
Not related to this repo, couldn't see a twitter link, so figured this was as good a way as any to reach out.

First, thanks a lot for this. Makes the whole process much easier than the other options I've seen.

https://alexlubbock.com/time-machine-network-backup-linux

I needed a couple of changes to get it working, one was adding `;yes;no` to the end of the `-s` block. This was necessary to get the second "read only" flag set to `no`, otherwise my share was read only.

I also had to copy the `_adisk._tcp` service block from here:

https://github.com/dperson/samba/blob/master/_etc_avahi_services_samba.service

Without that I wasn't able to see the share as an option in time machine, even though I could connect to it from my mac.

**Comment by chmac** [comment]
Oh yeah, and I also added the `-p` flag to the command, but I'm not sure if that was really necessary, as it was the `no` to the read only setting that finally meant I could write data...

**Comment by alubbock** [comment]
Glad you found the post useful. Thanks for taking the time to send feedback and help improve the post, and sorry for the slow response!

I've updated the post with your fixes.

Thanks again!
